### ISSUE TITLE
how do i get geckodriver and add it to PATH?

### ISSUE THREAD

**Issue by SharpBit** [quentintruong/RiceFarmer#1]
@quentintruong this README doesn't really say and I'm confused. Is this a python package?

**Comment by quentintruong** [comment]
Hi, try this link, it has info on installing geckodriver. Rice-Farmer is not a python package; it is just a script I wrote a while back. It probably does not work anymore due to outdated xpaths.
http://selenium-python.readthedocs.io/installation.html#drivers

**Comment by SharpBit** [comment]
I meant if geckodriver was a python package, not rice farmer lol. Anyway, thanks. I'll try it out but I found a JavaScript thing you can run in the browser's console (F12) and it worked. Appreciate your work though
